#!/bin/bash

source DayZLauncherUtil

workbenchExe=$(queryCfg "/config/tools/workbench/text()")
mods=""

verbosity=0

function printUsage() {
	printf "
- Usage
	DayZWorkbenchLauncher [-hv] [-m modsList] [-X exeFile]
	
- Options
	-h, --help                     Show this help.
	-v, --verbose                  Be verbose. Can be repeated for more verbosity
	-m, --mods <mods>              Loads the specified sub-folders for different mods.
	                                Separated by semi-colons. Absolute path and 
	                                multiple stacked folders are possible.

	-X, --exe <exe path>           Selects what executable file to be used
	    --script-define <define>   Specify to load a script preprocessor define.
	                                Can be repeated to define more.
"
}

function setupLaunchParameters() {
	local shortOpt="hvm:X:"
	local longOpt="help,verbose,mods:,exe:,script-define:"

	local parsedArgs=$(getopt -n DayZWorkbenchLauncher -o ${shortOpt} --long ${longOpt} -- "$@")
	if [ "$?" != "0" ]; then
		printUsage
		exit 1
	fi

	eval set -- "$parsedArgs"

	while true; do
		case $1 in
		-h | --help) printUsage; exit 1 ;;
		-v | --verbose) ((verbosity + 1)) ;;
		-m | --mods) addMod "$2"; shift ;;
		-X | --exe) setWorkbenchExe "$2"; shift ;;
		--)
			shift
			break
			;;
		*)
			echo "Invalid option: $1"
			printUsage
			exit 1
			;;
		esac
		shift #go to next arg
	done

	[[ -n $mods ]] && argMods="-mod=$mods"

}

function setWorkbenchExe() {
	if [ -n "$1" ]; then
		workbenchExe="$1"
	fi
}

function addMod() {
	if [ -n "$1" ]; then
		if [ -n "$mods" ]; then
			mods="$mods;$1"
		else
			mods="$1"
		fi
	fi
}

setupLaunchParameters "$@"

[[ $verbosity -ge 2 ]] && echo "cmd.exe" "/c" "START" "/D" "${workbenchExe%\\*}" ".\\${workbenchExe##*\\}" "$argMods"
cmd.exe /c "START" "/D" "${workbenchExe%\\*}" ".\\${workbenchExe##*\\}" "$argMods"
