#!/bin/bash

source DayZLauncherUtil

DAYZ_TOOLS="S:\Games\SteamLibrary\steamapps\common\DayZ Tools"
ADDON_BUILDER_EXE="$DAYZ_TOOLS\Bin\AddonBuilder\AddonBuilder.exe"

MOD_SRC_DIR=""
MOD_BUILD_DIR=""

launchArguments=()
declare -A launchValuedArguments

verbosity=0

function printUsage() {
	printf "
- Usage
	DayZModBuilder [-hvocbl] [-s sourcePath] [-d destinationPath] [-t tempFolderPath] [-p addonPrefix] [-P projectPath] [-k privateKey] [-K privateKey] [-i filesToInclude] [-e filesToExclude] [-V pboVersion] [-B binarize.exe] [-C cfgConvert.exe] [-F filebank.exe] [-D dssignfile.exe] [-T dayzToolsPath] 
	
- Options
	-h, --help                             Show this help.
	-v, --verbose                          Be verbose. Can be repeated for more verbosity.

	-o, --only-pack                        Only stores the folder to a PBO. Does NOT binarize 
	                                        files. (Binarization is default behaviour.)

	-c, --clear-temp                       Before binarizing, the content of subfolder for the 
	                                        current project is deleted.

	-b, -binarize-all-textures             Binarize all .TGA, .PNG textures even if they are not
	                                        referenced by any model or included in
	                                        any textures.lst file.

	-l, --extended-logs                    Enable extended logging	

	-t, --temp <folder>                    Path for the folder which stores binarized files, 
	                                        default destination is temp in Windows, if no 
	                                        value is present then the last folder is used, 
	                                        if you use the same folder, the next time you 
	                                        binarize the same addon it will take less time.

	-p, --prefix <prefix>                  Relative path to files used in addon, if not present
	                                        then this value is calculated automatically.

	-P, --project-path <path>              Path to folder where project starts from, if you are 
	                                        packing only the path of a project. It is recommended
	                                        to use the same as the source path or to define it
	                                        accordingly to the need. 
	                                        In case it is defined to P:, Binarize will process the
	                                        entire P: drive which takes time.

	-k, --sign-with <key>                  Private BI key (*.BIPRIVATEKEY) file that will be used
	                                        to sign the addon. Addons created with a signature can 
	                                        be added to secure servers.

	-K, --sign-with-copy <key>             Private BI key (*.BIPRIVATEKEY) file that will be used
	                                        to sign the addon. Addons created with a signature can 
	                                        be added to secure servers.
											The key will also be copied in the destination directory

	-i, --include <files>                  Directly copy matched files to PBO.
	                                        Absolute path to file with wildcard patterns.
	                                        Separator is ';' and ','.

	-e, --exclude <files>                  Absolute or relative file path. Contains patterns of
	                                        files which are excluded from final pbo. Look for
	                                        'exclude.lst' file in DayZTools install dir for
	                                        an example of exclude file content.

	-V, --pbo-version <version>            PBO version for FileBank (-property version=<version>)

	-B, --binarize-exe <exe>               Path to Binarize tool. Default Binarize tool is used
	                                        if not specified.
	
	-C, --cfgConvert-exe <exe>             Path to cfg convert tool. Default is used if not 
	                                        specified.

	-F, --filebank-exe <exe>               Path to cfg filebank tool. Default is used if not 
	                                        specified.

	-D, --dssignfile-exe <exe>             Path to cfg DssignFile  tool. Default is used if not 
	                                        specified.

	-T, --dayz-tools <folder>              Specifies the path to DayZ Tools directory with other 
	                                        tools (Binarize, CfgConvert, Filebank, ...). By default 
	                                        is the directory retrieved from Steam client.

	
"
}

function setupLaunchParameters() {
	shortOpt="hvocbls:d:t:p:P:k:K:i:e:V:B:C:F:D:T:"
	longOpt="help,verbose,only-pack,clear-temp,binarize-all-textures,extended-logs,source:,destination:,temp-folder:,prefix:,project-path:,sign-with:,sign-with-copy:,include:,exclude:,pbo-version:,binarize-exe:,cfgConvert-exe:,filebank-exe:,dssignfile-exe:,dayz-tools:"

	PARSED_ARGUMENTS=$(getopt -n DayZModBuilder -o ${shortOpt} --long ${longOpt} -- "$@")
	if [ "$?" != "0" ]; then
		printUsage
		exit 1
	fi

	eval set -- "$PARSED_ARGUMENTS"

	while true; do
		case $1 in
		-h | --help)
			printUsage
			exit 1
			;;
		-v | --verbose) ((verbosity++)) ;;

		-o | --only-pack) launchArguments+=("-packonly") ;;
		-c | --clear-temp) launchArguments+=("-clear") ;;
		-b | --binarize-all-textures) launchArguments+=("-binarizeAllTextures") ;;
		-l | --extended-logs) launchArguments+=("-binarizeFullLogs") ;;
		-s | --source)
			MOD_SRC_DIR="$2"
			shift
			;;
		-d | --destination)
			MOD_BUILD_DIR="$2"
			shift
			;;
		-t | --temp-folder)
			launchValuedArguments["-temp"]="$2"
			shift
			;;
		-p | --prefix)
			launchValuedArguments["-prefix"]="$2"
			shift
			;;
		-P | --project-path)
			launchValuedArguments["-project"]="$2"
			shift
			;;
		-k | --sign-with)
			launchValuedArguments["-sign"]="$2"
			shift
			;;
		-K | --sign-with-copy)
			launchValuedArguments["-sign"]="$2"
			willCopyKey=true
			shift
			;;
		-i | --include)
			launchValuedArguments["-include"]="$2"
			shift
			;;
		-e | --exclude)
			echo "WARNING: Exclude command is broken. Ignoring it. Edit the default exclude.lst file to exclude files"
			# launchValuedArguments["-exclude"]="$2"
			shift
			;;
		-V | --pbo-version)
			launchValuedArguments["-pboversion"]="$2"
			shift
			;;
		-B | --binarize-exe)
			launchValuedArguments["-binarize"]="$2"
			shift
			;;
		-C | --cfgConvert-exe)
			launchValuedArguments["-cfgconvert"]="$2"
			shift
			;;
		-F | --filebank-exe)
			launchValuedArguments["-filebank"]="$2"
			shift
			;;
		-D | --dssignfile-exe)
			launchValuedArguments["-dssignfile"]="$2"
			shift
			;;
		-T | --dayz-tools)
			launchValuedArguments["-toolsDirectory"]="$2"
			shift
			;;

		--)
			shift
			break
			;;
		*)
			echo "Invalid option: $1"
			printUsage
			exit 1
			;;
		esac
		shift #go to next arg
	done
}

function printLaunchParameters() {
	# Print launch arguments vertically
	local formattedArgs=$(echo "${launchArguments[*]} " | sed "s/-/\n|\t-/g" | sed "/| /d")

	echo "\
/=========================================================
|                Building mod
|
|-EXE: $ADDON_BUILDER_EXE 
|
|-MOD SOURCE:      ${MOD_SRC_DIR}
|-MOD DESTINATION: ${MOD_BUILD_DIR}
|
|-ARGUMENTS: $formattedArgs"
	for arg in "${!launchValuedArguments[@]}"; do
		echo "\
|	$arg = ${launchValuedArguments[$arg]}"
	done
}

function prepareValuedArguments() {
	local valuedArgs=()
	for arg in "${!launchValuedArguments[@]}"; do
		valuedArgs+=("$arg=${launchValuedArguments[$arg]}")
	done
	echo ${valuedArgs[*]}
}

function startAddonBuilderGUI() {
	cmd.exe "/c" "cd" "/D" "${ADDON_BUILDER_EXE%\\*}" "&&" ".\\${ADDON_BUILDER_EXE##*\\}"
}

function startAddonBuild() {
	cmd.exe "/c" "cd" "/D" "${ADDON_BUILDER_EXE%\\*}" "&&" ".\\${ADDON_BUILDER_EXE##*\\}" "$MOD_SRC_DIR" "$MOD_BUILD_DIR\Addons" ${launchArguments[*]} $(prepareValuedArguments)
}

function copyKey() {
	wMkdir "$MOD_BUILD_DIR\Keys"
	local publicKey="${launchValuedArguments[-sign]}"
	cmd.exe "/c" "copy" "${publicKey%.*}.bikey" "$MOD_BUILD_DIR\Keys" >/dev/null
}

#############################################
# MAIN
setupLaunchParameters $@

# Launche GUI
if [ -z "$MOD_SRC_DIR" ] && [ -z "$MOD_BUILD_DIR" ] && [ "${#launchArguments[@]}" -eq 0 ] && [ "${#launchValuedArguments[@]}" -eq 0 ]; then
	[[ $verbosity -ge 1 ]] && echo "No parameters specified, launching AddonBuilder GUI"
	case $verbosity in
	0 | 1) startAddonBuilderGUI >/dev/null 2>/dev/null ;;
	2) startAddonBuilderGUI >/dev/null ;;
	3) startAddonBuilderGUI ;;
	esac
	exit 1
fi

: ${MOD_SRC_DIR:?"A mod source directory MUST be defined!"}
: ${MOD_BUILD_DIR:?"A mod destination directory MUST be defined!"}

[[ $verbosity -ge 1 ]] && printLaunchParameters
[[ $verbosity -ge 2 ]] && echo "\
|---------------------------------------------------------
cmd.exe \"/c\" \"cd\" \"/D\" \"${ADDON_BUILDER_EXE%\\*}\" \"&&\" \".\\${ADDON_BUILDER_EXE##*\\}\" \"$MOD_SRC_DIR\" \"$MOD_BUILD_DIR\" ${launchArguments[*]} $(prepareValuedArguments)"
[[ $verbosity -ge 1 ]] && echo "\
|---------------------------------------------------------"

case $verbosity in
0 | 1) startAddonBuild >/dev/null 2>/dev/null ;;
2) startAddonBuild >/dev/null ;;
3) startAddonBuild ;;
esac

[[ $willCopyKey == true ]] && copyKey
